// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using oncalltool.Backend.Common.Data;

#nullable disable

namespace oncalltool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914122445_InitialOnCallDatabase")]
    partial class InitialOnCallDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("oncalltool.Backend.Common.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SchedulePrivilege")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("oncalltool.Backend.Common.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("oncalltool.Backend.Common.Models.OnCallSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DayType")
                        .HasColumnType("text");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("ImpactedPlatforms")
                        .HasColumnType("text");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("integer");

                    b.Property<string>("IncidentDescription")
                        .HasColumnType("text");

                    b.Property<int?>("PrimaryEmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryStatus")
                        .HasColumnType("text");

                    b.Property<int?>("SecondaryEmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceSheet")
                        .HasColumnType("text");

                    b.Property<string>("SwapNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryEmployeeId");

                    b.HasIndex("SecondaryEmployeeId");

                    b.HasIndex("DepartmentId", "Date")
                        .IsUnique();

                    b.ToTable("OnCallSchedules");
                });

            modelBuilder.Entity("oncalltool.Backend.Common.Models.AppUser", b =>
                {
                    b.HasOne("oncalltool.Backend.Common.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("oncalltool.Backend.Common.Models.OnCallSchedule", b =>
                {
                    b.HasOne("oncalltool.Backend.Common.Models.Department", "Department")
                        .WithMany("OnCallSchedules")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("oncalltool.Backend.Common.Models.AppUser", "PrimaryEmployee")
                        .WithMany()
                        .HasForeignKey("PrimaryEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("oncalltool.Backend.Common.Models.AppUser", "SecondaryEmployee")
                        .WithMany()
                        .HasForeignKey("SecondaryEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("PrimaryEmployee");

                    b.Navigation("SecondaryEmployee");
                });

            modelBuilder.Entity("oncalltool.Backend.Common.Models.Department", b =>
                {
                    b.Navigation("OnCallSchedules");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
