const contacts=[
 {team:'ERP Applications',area:'Enterprise Systems',name:'Ahmed Mohamed',phone:'+20 12 1000 4521',email:'ahmed.mohamed@company.com',initials:'AM'},
 {team:'Integration',area:'Digital Platforms',name:'Omar Hassan',phone:'+20 12 1834 0192',email:'omar.hassan@company.com',initials:'OH'},
 {team:'Database',area:'Infrastructure',name:'Mahmoud Ali',phone:'+20 10 7723 8841',email:'mahmoud.ali@company.com',initials:'MA'},
 {team:'Infrastructure',area:'Technology Operations',name:'Mostafa Ahmed',phone:'+20 11 0298 3317',email:'mostafa.ahmed@company.com',initials:'MA'},
 {team:'Network',area:'Technology Operations',name:'Sara Ibrahim',phone:'+20 12 4431 7655',email:'sara.ibrahim@company.com',initials:'SI'}
];
let preferred=contacts.map(x=>x.team);
const allTeams=[{name:'CRM',area:'Customer Platforms'},{name:'Billing',area:'Revenue Management'},{name:'Revenue Assurance',area:'Revenue Management'},{name:'Fraud Management',area:'Enterprise Systems'},{name:'Security Operations',area:'Cyber Security'},{name:'Data Warehouse',area:'Data & Analytics'},{name:'Data Analytics',area:'Data & Analytics'},{name:'Data Integration',area:'Data & Analytics'},...contacts.map(x=>({name:x.team,area:x.area}))];
const people=['Ahmed','Mohamed','Sara','Ahmed','Omar','Mohamed','Sara'];
const esc=s=>s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function renderContacts(filter=''){const data=contacts.filter(x=>preferred.includes(x.team)&&x.team.toLowerCase().includes(filter.toLowerCase()));document.querySelector('#nowView').innerHTML=data.length?data.map(x=>`<article class="contact-card"><div class="team-identity"><span class="team-icon">${esc(x.team[0])}</span><div><strong>${esc(x.team)}</strong><span>${esc(x.area)}</span></div></div><div class="person"><span class="avatar">${x.initials}</span><div class="person-meta"><strong>${esc(x.name)}</strong><small>${esc(x.phone)} · ${esc(x.email)}</small></div></div><div class="contact-actions"><a class="call-btn" href="tel:${x.phone.replace(/ /g,'')}">☎ Call</a><a class="mail-btn" href="mailto:${x.email}">Email</a></div></article>`).join(''):'<div style="padding:30px;text-align:center;color:#777">No preferred teams match your search.</div>'}
function renderChips(){document.querySelector('#preferredChips').innerHTML=preferred.map(x=>`<span class="chip">${esc(x)}<button data-remove="${esc(x)}" aria-label="Remove ${esc(x)}">×</button></span>`).join('')}
function renderWeek(){const days=['Wed 10','Thu 11','Fri 12','Sat 13','Sun 14','Mon 15','Tue 16'];document.querySelector('#weekView').innerHTML=`<table><thead><tr><th>Team</th>${days.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${preferred.map((t,j)=>`<tr><td><strong>${esc(t)}</strong></td>${days.map((_,i)=>`<td>${people[(i+j)%people.length]}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function renderTeamResults(q=''){const matches=allTeams.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())).filter(x=>!preferred.includes(x.name)).slice(0,6);document.querySelector('#teamResults').innerHTML=matches.length?matches.map(x=>`<div class="team-result"><div><strong>${esc(x.name)}</strong><small>${esc(x.area)}</small></div><button class="add-link" data-add="${esc(x.name)}">+ Add</button></div>`).join(''):'<div style="padding:25px 0;color:#777;text-align:center">No matching teams found.</div>'}
function openModal(id){document.querySelector(id).classList.remove('hidden')}function closeModals(){document.querySelectorAll('.modal-backdrop').forEach(x=>x.classList.add('hidden'))}
function swapPreview(){const [name,date]=document.querySelector('#swapSelect').value.split('|');document.querySelector('#swapPreview').innerHTML=`<div class="swap-state"><b>BEFORE</b><span>You → Wed, 9 Sep</span><span>${name} → ${date.split(', ')[1]}</span></div><div class="swap-state"><b>AFTER</b><span>${name} → Wed, 9 Sep</span><span>You → ${date.split(', ')[1]}</span></div>`}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#nowView').classList.toggle('hidden',b.dataset.view!=='now');document.querySelector('#weekView').classList.toggle('hidden',b.dataset.view!=='week');renderWeek()});
document.querySelector('#contactSearch').oninput=e=>renderContacts(e.target.value);document.querySelector('#preferredChips').onclick=e=>{if(e.target.dataset.remove){preferred=preferred.filter(x=>x!==e.target.dataset.remove);renderChips();renderContacts();renderWeek()}};document.querySelector('#teamResults').onclick=e=>{if(e.target.dataset.add){preferred.push(e.target.dataset.add);renderChips();renderContacts();renderTeamResults(document.querySelector('#teamSearch').value)}};document.querySelector('#teamSearch').oninput=e=>renderTeamResults(e.target.value);
document.querySelector('#addTeamBtn').onclick=()=>{openModal('#teamModal');renderTeamResults()};document.querySelector('#findTeamBtn').onclick=()=>{openModal('#teamModal');renderTeamResults()};document.querySelector('#swapBtn').onclick=()=>{openModal('#swapModal');swapPreview()};document.querySelector('#swapSelect').onchange=swapPreview;document.querySelectorAll('.close-modal').forEach(x=>x.onclick=closeModals);document.querySelectorAll('.modal-backdrop').forEach(x=>x.onclick=e=>{if(e.target===x)closeModals()});document.querySelector('#confirmSwap').onclick=()=>{closeModals();const t=document.querySelector('#toast');t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),3000)};document.querySelector('.mobile-menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
function tick(){document.querySelector('#currentTime').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date())}tick();setInterval(tick,60000);renderContacts();renderChips();renderWeek();
//aliiiiii